approvedGitRepositories:
  - "https://github.com/matter-labs/zksync-telemetry-js.git"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@wagmi/core@3.6.4":
    dependencies:
      accounts: "~0.14"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
